
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: fleetman-staff-service # just a name for this virtual service
  namespace: default
spec:
  hosts:
    - fleetman-staff-service.default.svc.cluster.local # The service DNS (ie the regular K8S Service) name that we are applying routing rule to.
    # Use the fully qualified domain name here. Need a FQDN when it is calling from a different namespace. 
    # https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/
  http:
    - route:
        - destination:
            host: fleetman-staff-service.default.svc.cluster.local # The target DNS name.
            subset: safe-group  # This point to the destination rule in the subset - name
          weight: 90
        - destination:
            host: fleetman-staff-service.default.svc.cluster.local # The target DNS name.
            subset: risky-group # This point to the destination rule in the subset - name
          weight: 10
---
kind: DestinationRule # Defining which pods should be part of each subset
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: fleetman-staff-service
  namespace: default
spec:
  host: fleetman-staff-service.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      consistentHash:
        useSourceIp: true
  subsets:
    - labels:   # SELECTOR
        version: safe   #Find pods with label safe -> in the application-no-istio.yaml we added version: safe and risky.
      name: safe-group
    - labels:
        version: risky
      name: risky-group